{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "18efbeca-b42a-402f-95f6-9249618971de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting uji_hipotesis_streamlit.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile uji_hipotesis_streamlit.py\n",
    "\n",
    "import streamlit as st\n",
    "import math\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "try:\n",
    "    from scipy import stats\n",
    "    SCIPY_AVAILABLE = True\n",
    "except:\n",
    "    SCIPY_AVAILABLE = False\n",
    "\n",
    "# ==============================================================\n",
    "# Page config\n",
    "# ==============================================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Pemilihan & Implementasi Uji Parametrik\", \n",
    "    layout=\"wide\",\n",
    "    page_icon=\"🌌\"\n",
    ")\n",
    "\n",
    "st.title(\"**📚Aplikasi Pemilihan & Implementasi Uji Parametrik (Berdasarkan Flowchart)**\")\n",
    "st.caption(\"Dibuat oleh: Kelompok (I.P.K 4) Kelas Pemrograman Komputer D\")\n",
    "\n",
    "# ==============================================================\n",
    "# 🌌 CUSTOM SPACE THEME (BLUE GALAXY)\n",
    "# ==============================================================\n",
    "\n",
    "space_css = \"\"\"\n",
    "<style>\n",
    "\n",
    "@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;600;800&display=swap');\n",
    "\n",
    "html, body, [class*=\"css\"]  {\n",
    "    font-family: 'Orbitron', sans-serif !important;\n",
    "    background: radial-gradient(circle at top, #001133, #000814, #00010f);\n",
    "    color: #e0eaff !important;\n",
    "}\n",
    "\n",
    "h1, h2, h3, h4 {\n",
    "    color: #78aaff !important;\n",
    "    text-shadow: 0 0 8px #4ea0ff;\n",
    "}\n",
    "\n",
    ".sidebar .sidebar-content {\n",
    "    background: #001a33;\n",
    "    color: white;\n",
    "}\n",
    "\n",
    ".css-1d391kg {\n",
    "    background: #001a33 !important;\n",
    "}\n",
    "\n",
    ".stButton>button {\n",
    "    background-color: #001f4d;\n",
    "    border: 1px solid #4ea0ff;\n",
    "    color: #cfe3ff;\n",
    "    padding: 0.6rem;\n",
    "    border-radius: 10px;\n",
    "    transition: 0.3s;\n",
    "}\n",
    "\n",
    ".stButton>button:hover {\n",
    "    background-color: #003f87;\n",
    "    border-color: #77b5ff;\n",
    "    transform: scale(1.05);\n",
    "}\n",
    "\n",
    ".stTabs [data-baseweb=\"tab\"] {\n",
    "    background: rgba(0, 34, 68, 0.7);\n",
    "    border-radius: 10px;\n",
    "    padding: 10px;\n",
    "    color: #99c2ff;\n",
    "    font-weight: 600;\n",
    "}\n",
    "\n",
    ".stTabs [aria-selected=\"true\"] {\n",
    "    background: rgba(0, 60, 120, 0.9);\n",
    "    color: #ffffff !important;\n",
    "    border-bottom: 2px solid #4ea0ff;\n",
    "}\n",
    "\n",
    ".reportview-container {\n",
    "    background: #000814;\n",
    "}\n",
    "\n",
    ".block-container {\n",
    "    padding-top: 1rem;\n",
    "}\n",
    "</style>\n",
    "\"\"\"\n",
    "\n",
    "st.markdown(space_css, unsafe_allow_html=True)\n",
    "\n",
    "# ==============================================================\n",
    "# SIDEBAR (Galaxy themed)\n",
    "# ==============================================================\n",
    "\n",
    "st.sidebar.markdown(\n",
    "    \"\"\"\n",
    "    <div style='text-align:center; padding:10px; color:#8db2ff'>\n",
    "        <h2>🚀 Menu Navigasi</h2>\n",
    "        <p>Eksplorasi galaksi uji parametrik</p>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "\n",
    "# -----------------------------------\n",
    "# Sidebar: navigasi utama\n",
    "# -----------------------------------\n",
    "st.sidebar.header(\"Menu Utama\")\n",
    "test_menu = st.sidebar.selectbox(\n",
    "    \"Pilih jenis uji statistik (setiap anggota kelompok menjelaskan 1 uji):\",\n",
    "    [\n",
    "        \"Flowchart (tampilan & upload)\",\n",
    "        \"Uji Proporsi 1 Sampel\",\n",
    "        \"Uji Proporsi 2 Sampel\",\n",
    "        \"Uji Rata-rata 1 Sampel (z jika σ diketahui)\",\n",
    "        \"Uji t 1 Sampel (σ tidak diketahui)\",\n",
    "        \"Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Z)\",\n",
    "        \"Uji Kesamaan Varians (F-test)\",\n",
    "        \"Uji Rata-rata 2 Sampel Independen — Varians Sama (Pooled t-test)\",\n",
    "        \"Uji Rata-rata 2 Sampel Independen — Varians Tidak Sama (Welch t-test)\",\n",
    "        \"Uji Rata-rata 2 Sampel Dependen (Paired t-test)\"\n",
    "    ]\n",
    ")\n",
    "st.sidebar.markdown(\n",
    "    \"\"\"\n",
    "    <div style='background:rgba(0,40,80,0.6);\n",
    "                padding:15px; \n",
    "                border-radius:12px; \n",
    "                margin-top:10px;\n",
    "                border:1px solid #4ea0ff;\n",
    "                box-shadow:0 0 8px #4ea0ff;'>\n",
    "        <h3 style='text-align:center; color:#9ec8ff;'>👩‍🚀 Anggota Kelompok (I.P.K 4):</h3>\n",
    "        <p style='text-align:center; color:#cfe3ff;'>\n",
    "            <li><strong>Tia Lisnawati</strong> — 140610250072</li>\n",
    "                <li><strong>Zerlina Aisyah</strong> — 140610250012</li>\n",
    "                   <li><strong>Naila Arziki Gunawan 140610250109</li>\n",
    "                        <li><strong>Fransiskus Asisi Listyo Nugroho 140610250085</li>\n",
    "                            <li><strong>Ghaisan Adlan Falah 140610250064</li>\n",
    "        </p>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "\n",
    "st.sidebar.caption(\"Aplikasi ini menyediakan penjelasan, rumus, contoh, dan kalkulator interaktif.\")\n",
    "\n",
    "# Utility: normal CDF and tail\n",
    "def normal_cdf(z):\n",
    "    return 0.5 * (1 + math.erf(z / math.sqrt(2)))\n",
    "\n",
    "def normal_sf(z):  # survival function for standard normal\n",
    "    return 1 - normal_cdf(z)\n",
    "\n",
    "def two_sided_p_from_z(z):\n",
    "    return 2 * normal_sf(abs(z))\n",
    "\n",
    "def one_sided_p_from_z(z, alternative):\n",
    "    if alternative == \"two-sided\":\n",
    "        return two_sided_p_from_z(z)\n",
    "    elif alternative == \"greater\":\n",
    "        # H1: parameter > H0 -> upper tail\n",
    "        return normal_sf(z)\n",
    "    else:\n",
    "        # \"less\": H1: parameter < H0 -> lower tail\n",
    "        return normal_cdf(z)\n",
    "\n",
    "# Flowchart display page\n",
    "if test_menu == \"Flowchart (tampilan & upload)\":\n",
    "    st.header(\"Flowchart Pemilihan Uji Statistik\")\n",
    "    st.markdown(\n",
    "        \"Unggah gambar flowchart yang diberikan dosen/kelompokmu (opsional). \"\n",
    "        \"Jika tidak diunggah, aplikasi menampilkan flowchart ilustratif sederhana.\"\n",
    "    )\n",
    "    uploaded = st.file_uploader(\"Upload flowchart (png/jpg/pdf):\", type=[\"png\", \"jpg\", \"jpeg\", \"pdf\"])\n",
    "    if uploaded:\n",
    "        st.image(uploaded, caption=\"Flowchart yang diunggah\", use_column_width=True)\n",
    "    else:\n",
    "        st.info(\"Tidak ada flowchart diunggah — menampilkan flowchart ilustratif berbasis graphviz.\")\n",
    "        # Simple illustrative flowchart via graphviz (Streamlit has st.graphviz_chart)\n",
    "        graph = \"\"\"\n",
    "        digraph {\n",
    "            node [shape=box, style=rounded];\n",
    "            Start -> \"Data & Tujuan uji\";\n",
    "            \"Data & Tujuan uji\" -> \"Parameter: proporsi / rata-rata / varians?\";\n",
    "            \"Parameter: proporsi / rata-rata / varians?\" -> Prop [label=\"proporsi\"];\n",
    "            \"Parameter: proporsi / rata-rata / varians?\" -> Mean [label=\"rata-rata\"];\n",
    "            \"Parameter: proporsi / rata-rata / varians?\" -> Var [label=\"varians\"];\n",
    "            Prop -> \"1 sampel atau 2 sampel?\";\n",
    "            Mean -> \"sigma diketahui? (z) : tidak (t)\";\n",
    "            \"2 sampel\" [shape=oval];\n",
    "            \"1 sampel atau 2 sampel?\" -> \"1 sampel\";\n",
    "            \"1 sampel atau 2 sampel?\" -> \"2 sampel\";\n",
    "            \"2 sampel\" -> \"independen atau dependen?\";\n",
    "            \"independen atau dependen?\" -> \"independen\";\n",
    "            \"independen atau dependen?\" -> \"dependent\";\n",
    "            \"independen\" -> \"cek kesamaan varians -> pooled t / welch\";\n",
    "            \"cek kesamaan varians -> pooled t / welch\" -> \"Uji kesamaan varians (F-test)\";\n",
    "        }\n",
    "        \"\"\"\n",
    "        st.graphviz_chart(graph)\n",
    "    st.markdown(\"---\")\n",
    "    st.write(\"Panduan singkat penggunaan aplikasi:\")\n",
    "    st.write(\n",
    "        \"- Pilih salah satu uji di sidebar untuk melihat penjelasan, rumus, contoh, dan kalkulator interaktif.\\n\"\n",
    "        \"- Gunakan tab di setiap halaman uji untuk berpindah bagian (Penjelasan, Hipotesis, Rumus, Parameter, Contoh, Kalkulasi, Nilai Kritis / p-value, Flowchart).\"\n",
    "    )\n",
    "\n",
    "# Helper to show tabs structure for any test: we will reuse\n",
    "def render_common_tabs(title):\n",
    "    return st.tabs([\"Penjelasan\", \"Hipotesis\", \"Rumus\", \"Parameter\", \"Contoh\", \"Kalkulasi Interaktif\", \"Nilai Kritis / p-value\", \"Referensi Flowchart\"])\n",
    "\n",
    "# Now implement each test page with tabs and interactive calculator\n",
    "# 1) Uji Proporsi 1 Sampel\n",
    "if test_menu == \"Uji Proporsi 1 Sampel\":\n",
    "    st.header(\"Uji Proporsi 1 Sampel\")\n",
    "    tabs = render_common_tabs(\"Proporsi 1 Sampel\")\n",
    "    # PENJELASAN\n",
    "    with tabs[0]:\n",
    "        st.markdown(\n",
    "            \"Uji proporsi 1 sampel digunakan untuk menguji hipotesis tentang proporsi populasi `p` \"\n",
    "            \"dengan data berupa jumlah keberhasilan `x` pada sampel ukuran `n`.\"\n",
    "        )\n",
    "        st.write(\"Contoh: apakah proporsi pengguna yang puas >= 0.6?\")\n",
    "    # HIPOTESIS\n",
    "    with tabs[1]:\n",
    "        st.write(\"Hipotesis umum:\")\n",
    "        st.latex(r\"H_0: p = p_0\")\n",
    "        st.latex(r\"H_1: p \\ne p_0 \\quad \\text{(atau >, < sesuai alternatif)}\")\n",
    "    # RUMUS\n",
    "    with tabs[2]:\n",
    "        st.write(\"Statistik uji (Z):\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{x}{n}\")\n",
    "        st.latex(r\"Z = \\frac{\\hat{p} - p_0}{\\sqrt{\\dfrac{p_0(1-p_0)}{n}}}\")\n",
    "    # PARAMETER\n",
    "    with tabs[3]:\n",
    "        st.write(\"- x: jumlah keberhasilan pada sampel\\n- n: ukuran sampel\\n- p0: proporsi hipotesis nol\\n- alternatif: two-sided / greater / less\")\n",
    "    # CONTOH\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat:\")\n",
    "        st.write(\"n=100, x=62, p0=0.6\")\n",
    "        phat = 62/100\n",
    "        z = (phat - 0.6)/math.sqrt(0.6*0.4/100)\n",
    "        pval = two_sided_p_from_z(z)\n",
    "        st.write(f\"phat = {phat:.3f}, Z = {z:.3f}, p-value(two-sided) ≈ {pval:.4f}\")\n",
    "    # KALKULASI INTERAKTIF\n",
    "    with tabs[5]:\n",
    "        st.subheader(\"Kalkulasi Proporsi 1 Sampel\")\n",
    "        n = st.number_input(\"Masukkan n (ukuran sampel):\", min_value=1, step=1, value=50)\n",
    "        x = st.number_input(\"Masukkan x (jumlah keberhasilan):\", min_value=0, step=1, value=30)\n",
    "        p0 = st.number_input(\"Masukkan p0 (proporsi H0):\", min_value=0.0, max_value=1.0, value=0.5, step=0.01)\n",
    "        alt = st.selectbox(\"Pilih alternatif H1:\", (\"two-sided\", \"greater\", \"less\"))\n",
    "        if st.button(\"Hitung Z & p-value (Proporsi 1 sampel)\"):\n",
    "            phat = x / n\n",
    "            se = math.sqrt(p0 * (1 - p0) / n)\n",
    "            z = (phat - p0) / se\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"phat = {phat:.4f}\")\n",
    "            st.write(f\"Z = {z:.4f}\")\n",
    "            st.write(f\"p-value (berdasarkan alternatif '{alt}') ≈ {p:.6f}\")\n",
    "            st.info(\"Keputusan: Bandingkan p-value dengan alpha (mis. 0.05) atau gunakan nilai kritis z.\")\n",
    "    # NILAI KRITIS / PVALUE\n",
    "    with tabs[6]:\n",
    "        st.write(\"Menentukan nilai kritis untuk z:\")\n",
    "        alpha = st.number_input(\"Alpha (signifikansi):\", min_value=0.0001, max_value=0.5, value=0.05, step=0.01)\n",
    "        if st.button(\"Tampilkan nilai kritis z\"):\n",
    "            if st.session_state.get('last_z') is None:\n",
    "                st.write(\"Nilai z/hitung pada tab Kalkulasi untuk membandingkan.\")\n",
    "            z_crit_two = abs(stats.norm.ppf(alpha/2)) if SCIPY_AVAILABLE else abs(math.sqrt(2) * math.erfinv(1 - alpha))\n",
    "            # note: math.erfinv may not be present in Python <3.8; using scipy preferable\n",
    "            try:\n",
    "                if SCIPY_AVAILABLE:\n",
    "                    z_crit_2 = abs(stats.norm.ppf(alpha/2))\n",
    "                    z_crit_upper = stats.norm.ppf(1-alpha)\n",
    "                    st.write(f\"Two-sided z critical ≈ ±{z_crit_2:.4f}\")\n",
    "                    st.write(f\"One-sided z critical ≈ {z_crit_upper:.4f} (upper)\")\n",
    "                else:\n",
    "                    st.warning(\"SciPy tidak tersedia — nilai kritis dihitung dengan aproksimasi.\")\n",
    "            except Exception:\n",
    "                st.warning(\"Silakan install scipy untuk nilai kritis numerik yang akurat.\")\n",
    "    # FLOWCHART\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart referensi untuk memilih uji proporsi: (lihat panel Flowchart utama atau unggah file)\")\n",
    "        st.info(\"Biasanya: apakah parameter proporsi? → apakah sampel 1 atau 2? → gunakan z-test proporsi.\")\n",
    "\n",
    "# 2) Uji Proporsi 2 Sampel\n",
    "if test_menu == \"Uji Proporsi 2 Sampel\":\n",
    "    st.header(\"Uji Proporsi 2 Sampel\")\n",
    "    tabs = render_common_tabs(\"Proporsi 2 Sampel\")\n",
    "    with tabs[0]:\n",
    "        st.markdown(\"Uji untuk membandingkan dua proporsi populasi p1 dan p2 (independen).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: p_1 = p_2\")\n",
    "        st.latex(r\"H_1: p_1 \\ne p_2 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"\\hat{p}_1 = x_1 / n_1,\\quad \\hat{p}_2 = x_2 / n_2\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{x_1 + x_2}{n_1 + n_2}\")\n",
    "        st.latex(r\"Z = \\frac{\\hat{p}_1 - \\hat{p}_2}{\\sqrt{\\hat{p}(1-\\hat{p})(\\frac{1}{n_1}+\\frac{1}{n_2})}}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: x1,x2,n1,n2, alternatif\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh: x1=30,n1=100 ; x2=20,n2=100\")\n",
    "        p1 = 30/100; p2 = 20/100; p_pooled = (30+20)/(100+100)\n",
    "        z = (p1-p2)/math.sqrt(p_pooled*(1-p_pooled)*(1/100+1/100))\n",
    "        st.write(f\"Z ≈ {z:.4f}, p(two-sided)≈{two_sided_p_from_z(z):.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.subheader(\"Kalkulasi Proporsi 2 Sampel\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=1, step=1, value=50, key=\"n1_prop2\")\n",
    "        x1 = st.number_input(\"x1:\", min_value=0, step=1, value=25, key=\"x1_prop2\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=1, step=1, value=50, key=\"n2_prop2\")\n",
    "        x2 = st.number_input(\"x2:\", min_value=0, step=1, value=20, key=\"x2_prop2\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_prop2\")\n",
    "        if st.button(\"Hitung (Proporsi 2 sampel)\"):\n",
    "            p1 = x1/n1; p2 = x2/n2\n",
    "            p_pool = (x1 + x2) / (n1 + n2)\n",
    "            se = math.sqrt(p_pool*(1-p_pool)*(1/n1 + 1/n2))\n",
    "            z = (p1 - p2) / se\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"p1={p1:.4f}, p2={p2:.4f}, Z={z:.4f}, p-value({alt})≈{p:.6f}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Menentukan nilai kritis z sama seperti uji proporsi 1 sampel.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: pilih proporsi → 2 sampel → gunakan pooled prop formula & z-test.\")\n",
    "\n",
    "# 3) Uji Rata-rata 1 Sampel (z jika sigma diketahui)\n",
    "if test_menu == \"Uji Rata-rata 1 Sampel (z jika σ diketahui)\":\n",
    "    st.header(\"Uji Rata-rata 1 Sampel (σ diketahui → Z-test)\")\n",
    "    tabs = render_common_tabs(\"1-Sample Mean (Z)\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila populasi variance (σ^2) diketahui atau sampel besar (n besar).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu = \\mu_0\")\n",
    "        st.latex(r\"H_1: \\mu \\ne \\mu_0 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"Z = \\frac{\\bar{x} - \\mu_0}{\\sigma / \\sqrt{n}}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbar, mu0, sigma, n\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh: xbar=52, mu0=50, sigma=5, n=36\")\n",
    "        z = (52-50)/(5/math.sqrt(36))\n",
    "        st.write(f\"Z = {z:.4f}, p(two-sided)≈{two_sided_p_from_z(z):.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Z 1-sample\")\n",
    "        xbar = st.number_input(\"Masukkan x̄:\", value=0.0, key=\"xbar_z1\")\n",
    "        mu0 = st.number_input(\"Masukkan µ0:\", value=0.0, key=\"mu0_z1\")\n",
    "        sigma = st.number_input(\"Masukkan σ (populasi):\", min_value=0.0001, value=1.0, key=\"sigma_z1\")\n",
    "        n = st.number_input(\"Masukkan n:\", min_value=1, step=1, value=30, key=\"n_z1\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_z1\")\n",
    "        if st.button(\"Hitung Z (1 sample)\"):\n",
    "            z = (xbar - mu0) / (sigma / math.sqrt(n))\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"Z = {z:.4f}, p-value({alt}) ≈ {p:.6f}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis z bisa dilihat dari distribusi normal (mis. ±1.96 untuk α=0.05 two-sided).\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: parameter rata-rata, sigma diketahui? → Z-test jika ya.\")\n",
    "\n",
    "# 4) Uji t 1 Sampel (sigma tidak diketahui)\n",
    "if test_menu == \"Uji t 1 Sampel (σ tidak diketahui)\":\n",
    "    st.header(\"Uji t 1 Sampel (σ tidak diketahui)\")\n",
    "    tabs = render_common_tabs(\"1-sample t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila σ populasi tidak diketahui dan n relatif kecil; gunakan s (sample sd).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu = \\mu_0\")\n",
    "        st.latex(r\"H_1: \\mu \\ne \\mu_0 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"t = \\frac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}, \\quad df = n - 1\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: data sampel (atau x̄ & s & n), µ0\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh (data langsung): gunakan data = [..]\")\n",
    "        st.write(\"Contoh singkat: xbar=5.2, s=1.1, n=10, mu0=5 => t = (5.2-5)/(1.1/√10)\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi t 1-sample\")\n",
    "        data_input = st.text_area(\"Masukkan data (pisahkan koma) atau kosongkan untuk input x̄, s, n\", value=\"\")\n",
    "        mu0 = st.number_input(\"Masukkan µ0:\", value=0.0, key=\"mu0_t1\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_t1\")\n",
    "        if st.button(\"Hitung t 1-sample\"):\n",
    "            try:\n",
    "                if data_input.strip():\n",
    "                    arr = np.array(list(map(float, data_input.split(\",\"))))\n",
    "                    n = len(arr)\n",
    "                    xbar = arr.mean()\n",
    "                    s = arr.std(ddof=1)\n",
    "                else:\n",
    "                    xbar = st.number_input(\"Masukkan x̄:\", value=0.0, key=\"xbar_t1_manual\")\n",
    "                    s = st.number_input(\"Masukkan s (sample sd):\", min_value=0.0001, value=1.0, key=\"s_t1_manual\")\n",
    "                    n = st.number_input(\"Masukkan n:\", min_value=2, step=1, value=10, key=\"n_t1_manual\")\n",
    "                t_stat = (xbar - mu0) / (s / math.sqrt(n))\n",
    "                df = n - 1\n",
    "                if SCIPY_AVAILABLE:\n",
    "                    if alt == \"two-sided\":\n",
    "                        p = 2 * stats.t.sf(abs(t_stat), df)\n",
    "                    elif alt == \"greater\":\n",
    "                        p = stats.t.sf(t_stat, df)\n",
    "                    else:\n",
    "                        p = stats.t.cdf(t_stat, df)\n",
    "                    st.write(f\"t = {t_stat:.4f}, df = {df}, p-value ({alt}) = {p:.6f}\")\n",
    "                else:\n",
    "                    st.write(\"t = {:.4f}, df = {}\".format(t_stat, df))\n",
    "                    st.warning(\"Untuk p-value akurat, install scipy (pip install scipy).\")\n",
    "            except Exception as e:\n",
    "                st.error(f\"Error: {e}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis t didapat dari distribusi t dengan df = n-1 (gunakan tabel t atau scipy.stats.t.ppf).\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: µ? sigma diketahui? jika tidak → gunakan t 1-sample.\")\n",
    "\n",
    "# 5) Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Uji Z)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Z)\":\n",
    "    st.header(\"Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Z-test)\")\n",
    "    tabs = render_common_tabs(\"2-sample mean z\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila kedua populasi varians diketahui (jarang), atau aproksimasi untuk n besar.\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_1 = \\mu_2\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne \\mu_2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"Z = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbar1,xbar2, sigma1, sigma2, n1,n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: x1bar=10, x2bar=8, sigma1=2, sigma2=3, n1=40, n2=35\")\n",
    "        z = (10-8)/math.sqrt(2**2/40 + 3**2/35)\n",
    "        st.write(f\"Z ≈ {z:.4f}, p(two-sided)≈{two_sided_p_from_z(z):.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Z 2-sample (varians diketahui)\")\n",
    "        x1 = st.number_input(\"x̄1:\", value=0.0, key=\"x1_z2\")\n",
    "        x2 = st.number_input(\"x̄2:\", value=0.0, key=\"x2_z2\")\n",
    "        s1 = st.number_input(\"σ1 (populasi):\", min_value=0.0001, value=1.0, key=\"sig1_z2\")\n",
    "        s2 = st.number_input(\"σ2 (populasi):\", min_value=0.0001, value=1.0, key=\"sig2_z2\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=1, step=1, value=30, key=\"n1_z2\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=1, step=1, value=30, key=\"n2_z2\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_z2\")\n",
    "        if st.button(\"Hitung Z (2-sample known var)\"):\n",
    "            z = (x1 - x2) / math.sqrt(s1**2 / n1 + s2**2 / n2)\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"Z = {z:.4f}, p-value ({alt}) ≈ {p:.6f}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis sama dengan uji z lainnya.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: dua sampel independen & varians diketahui -> gunakan z-test 2 sampel.\")\n",
    "\n",
    "# 6) Uji Kesamaan Varians (F-test)\n",
    "if test_menu == \"Uji Kesamaan Varians (F-test)\":\n",
    "    st.header(\"Uji Kesamaan Varians (F-test)\")\n",
    "    tabs = render_common_tabs(\"F-test\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Uji F untuk membandingkan dua varians: H0: σ1^2 = σ2^2\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\sigma_1^2 = \\sigma_2^2\")\n",
    "        st.latex(r\"H_1: \\sigma_1^2 \\ne \\sigma_2^2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"F = \\frac{s_1^2}{s_2^2}, \\quad df_1 = n_1-1, \\ df_2 = n_2-1\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: sample variances s1^2, s2^2, n1, n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: s1^2=4, s2^2=2, n1=10, n2=12\")\n",
    "        F = 4/2\n",
    "        st.write(f\"F = {F:.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi F-test\")\n",
    "        s1sq = st.number_input(\"s1^2 (var sampel 1):\", min_value=0.0, value=4.0, key=\"s1sq\")\n",
    "        s2sq = st.number_input(\"s2^2 (var sampel 2):\", min_value=0.0, value=2.0, key=\"s2sq\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=2, step=1, value=10, key=\"n1_f\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=2, step=1, value=12, key=\"n2_f\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_f\")\n",
    "        if st.button(\"Hitung F\"):\n",
    "            if s2sq == 0:\n",
    "                st.error(\"s2^2 tidak boleh 0.\")\n",
    "            else:\n",
    "                F = s1sq / s2sq\n",
    "                df1 = n1 - 1\n",
    "                df2 = n2 - 1\n",
    "                st.write(f\"F = {F:.4f}, df1={df1}, df2={df2}\")\n",
    "                if SCIPY_AVAILABLE:\n",
    "                    if alt == \"two-sided\":\n",
    "                        # two-sided: p = 2 * min(P(F>f), P(F<f))\n",
    "                        p_upper = stats.f.sf(F, df1, df2)\n",
    "                        p_lower = stats.f.cdf(F, df1, df2)\n",
    "                        p = 2 * min(p_upper, p_lower)\n",
    "                    elif alt == \"greater\":\n",
    "                        p = stats.f.sf(F, df1, df2)\n",
    "                    else:\n",
    "                        p = stats.f.cdf(F, df1, df2)\n",
    "                    st.write(f\"p-value ({alt}) = {p:.6f}\")\n",
    "                else:\n",
    "                    st.warning(\"Untuk p-value akurat, install scipy (pip install scipy).\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Menentukan nilai kritis F: gunakan tabel F atau scipy.stats.f.ppf.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika membandingkan varians dua sampel → gunakan F-test untuk check equal variances.\")\n",
    "\n",
    "# 7) Pooled t-test (equal variances)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Independen — Varians Sama (Pooled t-test)\":\n",
    "    st.header(\"Pooled t-test (Two-sample t, equal variances)\")\n",
    "    tabs = render_common_tabs(\"Pooled t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Untuk dua sampel independen dengan asumsi varians populasi sama.\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_1 = \\mu_2\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne \\mu_2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"s_p^2 = \\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}\")\n",
    "        st.latex(r\"t = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}},\\quad df = n_1+n_2-2\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbar1,xbar2,s1,s2,n1,n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: x1bar=5, x2bar=3, s1=1.2, s2=1.1, n1=12, n2=10\")\n",
    "        sp2 = ((12-1)*1.2**2 + (10-1)*1.1**2) / (12+10-2)\n",
    "        t = (5-3)/(math.sqrt(sp2)*math.sqrt(1/12+1/10))\n",
    "        st.write(f\"t ≈ {t:.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Pooled t\")\n",
    "        x1 = st.number_input(\"x̄1:\", value=0.0, key=\"x1_pt\")\n",
    "        x2 = st.number_input(\"x̄2:\", value=0.0, key=\"x2_pt\")\n",
    "        s1 = st.number_input(\"s1 (sd sampel):\", min_value=0.0001, value=1.0, key=\"s1_pt\")\n",
    "        s2 = st.number_input(\"s2 (sd sampel):\", min_value=0.0001, value=1.0, key=\"s2_pt\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=2, step=1, value=12, key=\"n1_pt\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=2, step=1, value=10, key=\"n2_pt\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_pt\")\n",
    "        if st.button(\"Hitung Pooled t\"):\n",
    "            sp2 = ((n1-1)*s1**2 + (n2-1)*s2**2) / (n1 + n2 - 2)\n",
    "            sp = math.sqrt(sp2)\n",
    "            t_stat = (x1 - x2) / (sp * math.sqrt(1/n1 + 1/n2))\n",
    "            df = n1 + n2 - 2\n",
    "            if SCIPY_AVAILABLE:\n",
    "                if alt == \"two-sided\":\n",
    "                    p = 2 * stats.t.sf(abs(t_stat), df)\n",
    "                elif alt == \"greater\":\n",
    "                    p = stats.t.sf(t_stat, df)\n",
    "                else:\n",
    "                    p = stats.t.cdf(t_stat, df)\n",
    "                st.write(f\"t = {t_stat:.4f}, df = {df}, p-value ({alt}) = {p:.6f}\")\n",
    "            else:\n",
    "                st.write(f\"t = {t_stat:.4f}, df = {df}\")\n",
    "                st.warning(\"Install scipy untuk p-value akurat.\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis t: gunakan t-table atau scipy.stats.t.ppf dengan df = n1+n2-2.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika equal variances TRUE → gunakan pooled t-test.\")\n",
    "\n",
    "# 8) Welch t-test (varians tidak sama)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Independen — Varians Tidak Sama (Welch t-test)\":\n",
    "    st.header(\"Welch t-test (Two-sample t, unequal variances)\")\n",
    "    tabs = render_common_tabs(\"Welch t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila varians populasi kedua kelompok tidak sama.\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_1 = \\mu_2\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne \\mu_2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{s_1^2/n_1 + s_2^2/n_2}}\")\n",
    "        st.latex(r\"\\nu \\approx \\frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\\frac{(s_1^2/n_1)^2}{n_1-1} + \\frac{(s_2^2/n_2)^2}{n_2-1}}  \\quad \\text{(Welch–Satterthwaite)}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbars, s1,s2, n1,n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: x1bar=8, x2bar=6, s1=2, s2=3, n1=15, n2=12\")\n",
    "        t = (8-6)/math.sqrt(2**2/15 + 3**2/12)\n",
    "        st.write(f\"t ≈ {t:.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Welch t\")\n",
    "        x1 = st.number_input(\"x̄1:\", value=0.0, key=\"x1_welch\")\n",
    "        x2 = st.number_input(\"x̄2:\", value=0.0, key=\"x2_welch\")\n",
    "        s1 = st.number_input(\"s1 (sd):\", min_value=0.0001, value=1.0, key=\"s1_welch\")\n",
    "        s2 = st.number_input(\"s2 (sd):\", min_value=0.0001, value=1.0, key=\"s2_welch\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=2, step=1, value=15, key=\"n1_welch\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=2, step=1, value=12, key=\"n2_welch\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_welch\")\n",
    "        if st.button(\"Hitung Welch t\"):\n",
    "            numerator = (s1**2 / n1 + s2**2 / n2)**2\n",
    "            denom = ( (s1**2 / n1)**2 / (n1 - 1) ) + ( (s2**2 / n2)**2 / (n2 - 1) )\n",
    "            df_approx = numerator / denom if denom != 0 else 1\n",
    "            t_stat = (x1 - x2) / math.sqrt(s1**2 / n1 + s2**2 / n2)\n",
    "            if SCIPY_AVAILABLE:\n",
    "                if alt == \"two-sided\":\n",
    "                    p = 2 * stats.t.sf(abs(t_stat), df_approx)\n",
    "                elif alt == \"greater\":\n",
    "                    p = stats.t.sf(t_stat, df_approx)\n",
    "                else:\n",
    "                    p = stats.t.cdf(t_stat, df_approx)\n",
    "                st.write(f\"t = {t_stat:.4f}, df ≈ {df_approx:.2f}, p-value({alt}) = {p:.6f}\")\n",
    "            else:\n",
    "                st.write(f\"t = {t_stat:.4f}, df ≈ {df_approx:.2f}\")\n",
    "                st.warning(\"Install scipy untuk p-value akurat.\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis: gunakan distribusi t dengan df ditentukan oleh formula Welch–Satterthwaite.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika equal variances FALSE → gunakan Welch t-test.\")\n",
    "\n",
    "# 9) Paired t-test (dependent samples)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Dependen (Paired t-test)\":\n",
    "    st.header(\"Paired t-test (2-sample dependent)\")\n",
    "    tabs = render_common_tabs(\"Paired t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan ketika observasi berpasangan (mis. sebelum-sesudah pada subjek yang sama).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_d = 0 \\quad \\text{(sering)}\")\n",
    "        st.latex(r\"H_1: \\mu_d \\ne 0 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"d_i = x_i - y_i,\\quad \\bar{d} = \\frac{1}{n}\\sum d_i\")\n",
    "        st.latex(r\"t = \\frac{\\bar{d} - \\mu_{d,0}}{s_d / \\sqrt{n}},\\quad df = n-1\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: pasangan data X dan Y (per baris), atau masukkan beda secara langsung.\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: X = [10,12,11], Y = [9,11,10] → d=[1,1,1] → t ...\")\n",
    "        d = np.array([1,1,1])\n",
    "        st.write(f\"d mean = {d.mean():.3f}, sd(d) = {d.std(ddof=1):.3f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Paired t\")\n",
    "        data_X = st.text_area(\"Masukkan data X (pisahkan koma):\", value=\"\")\n",
    "        data_Y = st.text_area(\"Masukkan data Y (pisahkan koma):\", value=\"\")\n",
    "        mu_d0 = st.number_input(\"µ_d0 (null difference):\", value=0.0, key=\"mud0\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_paired\")\n",
    "        if st.button(\"Hitung Paired t\"):\n",
    "            try:\n",
    "                X = np.array(list(map(float, data_X.split(\",\"))))\n",
    "                Y = np.array(list(map(float, data_Y.split(\",\"))))\n",
    "                if len(X) != len(Y):\n",
    "                    st.error(\"Panjang data X dan Y harus sama.\")\n",
    "                else:\n",
    "                    d = X - Y\n",
    "                    n = len(d)\n",
    "                    dbar = d.mean()\n",
    "                    sd = d.std(ddof=1)\n",
    "                    t_stat = (dbar - mu_d0) / (sd / math.sqrt(n))\n",
    "                    df = n - 1\n",
    "                    if SCIPY_AVAILABLE:\n",
    "                        if alt == \"two-sided\":\n",
    "                            p = 2 * stats.t.sf(abs(t_stat), df)\n",
    "                        elif alt == \"greater\":\n",
    "                            p = stats.t.sf(t_stat, df)\n",
    "                        else:\n",
    "                            p = stats.t.cdf(t_stat, df)\n",
    "                        st.write(f\"t = {t_stat:.4f}, df = {df}, p-value({alt}) = {p:.6f}\")\n",
    "                    else:\n",
    "                        st.write(f\"t = {t_stat:.4f}, df = {df}\")\n",
    "                        st.warning(\"Install scipy untuk p-value akurat.\")\n",
    "            except Exception as e:\n",
    "                st.error(f\"Error parsing data: {e}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis t: gunakan t-table dengan df = n-1.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika dua sampel dependen → gunakan paired t-test.\")\n",
    "\n",
    "# Footer / help\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\n",
    "    \"**Catatan:***\\n\"\n",
    "    \"- Pastikan memahami asumsi tiap uji (normalitas, independensi, ukuran sampel, dsb.).\\n\"\n",
    "    \"- Untuk p-value distribusi t/F presisi, sebaiknya install `scipy` (`pip install scipy`).\\n\"\n",
    "    \"- Aplikasi ini menampilkan rumus, contoh singkat, dan kalkulator interaktif untuk membantu penentuan uji.\\n\"\n",
    "    \"- Jika kamu punya flowchart yang diberikan dosen, unggah di menu **Flowchart** untuk referensi kelompok.\"\n",
    ")\n",
    "if not SCIPY_AVAILABLE:\n",
    "    st.warning(\"Modul scipy tidak tersedia pada environment ini — beberapa p-value (t, F) tidak dihitung otomatis. \"\n",
    "               \"Install scipy untuk hasil numerik lengkap: pip install scipy\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c35c5a98-4ba9-47a7-abea-656d811d6891",
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run uji_hipotesis_streamlit.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9214ff8e-a8d3-4a97-a139-ae048fed2bb7",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%writefile uji_hipotesis_streamlit.py\n",
    "\n",
    "import streamlit as st\n",
    "import math\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "try:\n",
    "    from scipy import stats\n",
    "    SCIPY_AVAILABLE = True\n",
    "except:\n",
    "    SCIPY_AVAILABLE = False\n",
    "\n",
    "# ==============================================================\n",
    "# Page config\n",
    "# ==============================================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Pemilihan & Implementasi Uji Parametrik\", \n",
    "    layout=\"wide\",\n",
    "    page_icon=\"🌌\"\n",
    ")\n",
    "\n",
    "st.title(\"**📚Aplikasi Pemilihan & Implementasi Uji Parametrik (Berdasarkan Flowchart)**\")\n",
    "st.caption(\"Dibuat oleh: Kelompok (I.P.K 4) Kelas Pemrograman Komputer D\")\n",
    "\n",
    "# ==============================================================\n",
    "# 🌌 CUSTOM SPACE THEME (BLUE GALAXY)\n",
    "# ==============================================================\n",
    "\n",
    "space_css = \"\"\"\n",
    "<style>\n",
    "\n",
    "@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;600;800&display=swap');\n",
    "\n",
    "html, body, [class*=\"css\"]  {\n",
    "    font-family: 'Orbitron', sans-serif !important;\n",
    "    background: radial-gradient(circle at top, #001133, #000814, #00010f);\n",
    "    color: #e0eaff !important;\n",
    "}\n",
    "\n",
    "h1, h2, h3, h4 {\n",
    "    color: #78aaff !important;\n",
    "    text-shadow: 0 0 8px #4ea0ff;\n",
    "}\n",
    "\n",
    ".sidebar .sidebar-content {\n",
    "    background: #001a33;\n",
    "    color: white;\n",
    "}\n",
    "\n",
    ".css-1d391kg {\n",
    "    background: #001a33 !important;\n",
    "}\n",
    "\n",
    ".stButton>button {\n",
    "    background-color: #001f4d;\n",
    "    border: 1px solid #4ea0ff;\n",
    "    color: #cfe3ff;\n",
    "    padding: 0.6rem;\n",
    "    border-radius: 10px;\n",
    "    transition: 0.3s;\n",
    "}\n",
    "\n",
    ".stButton>button:hover {\n",
    "    background-color: #003f87;\n",
    "    border-color: #77b5ff;\n",
    "    transform: scale(1.05);\n",
    "}\n",
    "\n",
    ".stTabs [data-baseweb=\"tab\"] {\n",
    "    background: rgba(0, 34, 68, 0.7);\n",
    "    border-radius: 10px;\n",
    "    padding: 10px;\n",
    "    color: #99c2ff;\n",
    "    font-weight: 600;\n",
    "}\n",
    "\n",
    ".stTabs [aria-selected=\"true\"] {\n",
    "    background: rgba(0, 60, 120, 0.9);\n",
    "    color: #ffffff !important;\n",
    "    border-bottom: 2px solid #4ea0ff;\n",
    "}\n",
    "\n",
    ".reportview-container {\n",
    "    background: #000814;\n",
    "}\n",
    "\n",
    ".block-container {\n",
    "    padding-top: 1rem;\n",
    "}\n",
    "</style>\n",
    "\"\"\"\n",
    "\n",
    "st.markdown(space_css, unsafe_allow_html=True)\n",
    "\n",
    "# ==============================================================\n",
    "# SIDEBAR (Galaxy themed)\n",
    "# ==============================================================\n",
    "\n",
    "st.sidebar.markdown(\n",
    "    \"\"\"\n",
    "    <div style='text-align:center; padding:10px; color:#8db2ff'>\n",
    "        <h2>🚀 Menu Navigasi</h2>\n",
    "        <p>Eksplorasi galaksi uji parametrik</p>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "\n",
    "# -----------------------------------\n",
    "# Sidebar: navigasi utama\n",
    "# -----------------------------------\n",
    "st.sidebar.header(\"Menu Utama\")\n",
    "test_menu = st.sidebar.selectbox(\n",
    "    \"Pilih jenis uji statistik (setiap anggota kelompok menjelaskan 1 uji):\",\n",
    "    [\n",
    "        \"Flowchart (tampilan & upload)\",\n",
    "        \"Uji Proporsi 1 Sampel\",\n",
    "        \"Uji Proporsi 2 Sampel\",\n",
    "        \"Uji Rata-rata 1 Sampel (z jika σ diketahui)\",\n",
    "        \"Uji t 1 Sampel (σ tidak diketahui)\",\n",
    "        \"Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Z)\",\n",
    "        \"Uji Kesamaan Varians (F-test)\",\n",
    "        \"Uji Rata-rata 2 Sampel Independen — Varians Sama (Pooled t-test)\",\n",
    "        \"Uji Rata-rata 2 Sampel Independen — Varians Tidak Sama (Welch t-test)\",\n",
    "        \"Uji Rata-rata 2 Sampel Dependen (Paired t-test)\"\n",
    "    ]\n",
    ")\n",
    "st.sidebar.markdown(\n",
    "    \"\"\"\n",
    "    <div style='background:rgba(0,40,80,0.6);\n",
    "                padding:15px; \n",
    "                border-radius:12px; \n",
    "                margin-top:10px;\n",
    "                border:1px solid #4ea0ff;\n",
    "                box-shadow:0 0 8px #4ea0ff;'>\n",
    "        <h3 style='text-align:center; color:#9ec8ff;'>👩‍🚀 Anggota Kelompok (I.P.K 4):</h3>\n",
    "        <p style='text-align:center; color:#cfe3ff;'>\n",
    "            <li><strong>Tia Lisnawati</strong> — 140610250072</li>\n",
    "                <li><strong>Zerlina Aisyah</strong> — 140610250012</li>\n",
    "                   <li><strong>Naila Arziki Gunawan 140610250109</li>\n",
    "                        <li><strong>Fransiskus Asisi Listyo Nugroho 140610250085</li>\n",
    "                            <li><strong>Ghaisan Adlan Falah 140610250064</li>\n",
    "        </p>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "\n",
    "st.sidebar.caption(\"Aplikasi ini menyediakan penjelasan, rumus, contoh, dan kalkulator interaktif.\")\n",
    "\n",
    "# Utility: normal CDF and tail\n",
    "def normal_cdf(z):\n",
    "    return 0.5 * (1 + math.erf(z / math.sqrt(2)))\n",
    "\n",
    "def normal_sf(z):  # survival function for standard normal\n",
    "    return 1 - normal_cdf(z)\n",
    "\n",
    "def two_sided_p_from_z(z):\n",
    "    return 2 * normal_sf(abs(z))\n",
    "\n",
    "def one_sided_p_from_z(z, alternative):\n",
    "    if alternative == \"two-sided\":\n",
    "        return two_sided_p_from_z(z)\n",
    "    elif alternative == \"greater\":\n",
    "        # H1: parameter > H0 -> upper tail\n",
    "        return normal_sf(z)\n",
    "    else:\n",
    "        # \"less\": H1: parameter < H0 -> lower tail\n",
    "        return normal_cdf(z)\n",
    "\n",
    "# Flowchart display page\n",
    "if test_menu == \"Flowchart (tampilan & upload)\":\n",
    "    st.header(\"Flowchart Pemilihan Uji Statistik\")\n",
    "    st.markdown(\n",
    "        \"Unggah gambar flowchart yang diberikan dosen/kelompokmu (opsional). \"\n",
    "        \"Jika tidak diunggah, aplikasi menampilkan flowchart ilustratif sederhana.\"\n",
    "    )\n",
    "    uploaded = st.file_uploader(\"Upload flowchart (png/jpg/pdf):\", type=[\"png\", \"jpg\", \"jpeg\", \"pdf\"])\n",
    "    if uploaded:\n",
    "        st.image(uploaded, caption=\"Flowchart yang diunggah\", use_column_width=True)\n",
    "    else:\n",
    "        st.info(\"Tidak ada flowchart diunggah — menampilkan flowchart ilustratif berbasis graphviz.\")\n",
    "        # Simple illustrative flowchart via graphviz (Streamlit has st.graphviz_chart)\n",
    "        graph = \"\"\"\n",
    "        digraph {\n",
    "            node [shape=box, style=rounded];\n",
    "            Start -> \"Data & Tujuan uji\";\n",
    "            \"Data & Tujuan uji\" -> \"Parameter: proporsi / rata-rata / varians?\";\n",
    "            \"Parameter: proporsi / rata-rata / varians?\" -> Prop [label=\"proporsi\"];\n",
    "            \"Parameter: proporsi / rata-rata / varians?\" -> Mean [label=\"rata-rata\"];\n",
    "            \"Parameter: proporsi / rata-rata / varians?\" -> Var [label=\"varians\"];\n",
    "            Prop -> \"1 sampel atau 2 sampel?\";\n",
    "            Mean -> \"sigma diketahui? (z) : tidak (t)\";\n",
    "            \"2 sampel\" [shape=oval];\n",
    "            \"1 sampel atau 2 sampel?\" -> \"1 sampel\";\n",
    "            \"1 sampel atau 2 sampel?\" -> \"2 sampel\";\n",
    "            \"2 sampel\" -> \"independen atau dependen?\";\n",
    "            \"independen atau dependen?\" -> \"independen\";\n",
    "            \"independen atau dependen?\" -> \"dependent\";\n",
    "            \"independen\" -> \"cek kesamaan varians -> pooled t / welch\";\n",
    "            \"cek kesamaan varians -> pooled t / welch\" -> \"Uji kesamaan varians (F-test)\";\n",
    "        }\n",
    "        \"\"\"\n",
    "        st.graphviz_chart(graph)\n",
    "    st.markdown(\"---\")\n",
    "    st.write(\"Panduan singkat penggunaan aplikasi:\")\n",
    "    st.write(\n",
    "        \"- Pilih salah satu uji di sidebar untuk melihat penjelasan, rumus, contoh, dan kalkulator interaktif.\\n\"\n",
    "        \"- Gunakan tab di setiap halaman uji untuk berpindah bagian (Penjelasan, Hipotesis, Rumus, Parameter, Contoh, Kalkulasi, Nilai Kritis / p-value, Flowchart).\"\n",
    "    )\n",
    "\n",
    "# Helper to show tabs structure for any test: we will reuse\n",
    "def render_common_tabs(title):\n",
    "    return st.tabs([\"Penjelasan\", \"Hipotesis\", \"Rumus\", \"Parameter\", \"Contoh\", \"Kalkulasi Interaktif\", \"Nilai Kritis / p-value\", \"Referensi Flowchart\"])\n",
    "\n",
    "# Now implement each test page with tabs and interactive calculator\n",
    "# 1) Uji Proporsi 1 Sampel\n",
    "if test_menu == \"Uji Proporsi 1 Sampel\":\n",
    "    st.header(\"Uji Proporsi 1 Sampel\")\n",
    "    tabs = render_common_tabs(\"Proporsi 1 Sampel\")\n",
    "    # PENJELASAN\n",
    "    with tabs[0]:\n",
    "        st.markdown(\n",
    "            \"Uji proporsi 1 sampel digunakan untuk menguji hipotesis tentang proporsi populasi `p` \"\n",
    "            \"dengan data berupa jumlah keberhasilan `x` pada sampel ukuran `n`.\"\n",
    "        )\n",
    "        st.write(\"Contoh: apakah proporsi pengguna yang puas >= 0.6?\")\n",
    "    # HIPOTESIS\n",
    "    with tabs[1]:\n",
    "        st.write(\"Hipotesis umum:\")\n",
    "        st.latex(r\"H_0: p = p_0\")\n",
    "        st.latex(r\"H_1: p \\ne p_0 \\quad \\text{(atau >, < sesuai alternatif)}\")\n",
    "    # RUMUS\n",
    "    with tabs[2]:\n",
    "        st.write(\"Statistik uji (Z):\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{x}{n}\")\n",
    "        st.latex(r\"Z = \\frac{\\hat{p} - p_0}{\\sqrt{\\dfrac{p_0(1-p_0)}{n}}}\")\n",
    "    # PARAMETER\n",
    "    with tabs[3]:\n",
    "        st.write(\"- x: jumlah keberhasilan pada sampel\\n- n: ukuran sampel\\n- p0: proporsi hipotesis nol\\n- alternatif: two-sided / greater / less\")\n",
    "    # CONTOH\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat:\")\n",
    "        st.write(\"n=100, x=62, p0=0.6\")\n",
    "        phat = 62/100\n",
    "        z = (phat - 0.6)/math.sqrt(0.6*0.4/100)\n",
    "        pval = two_sided_p_from_z(z)\n",
    "        st.write(f\"phat = {phat:.3f}, Z = {z:.3f}, p-value(two-sided) ≈ {pval:.4f}\")\n",
    "    # KALKULASI INTERAKTIF\n",
    "    with tabs[5]:\n",
    "        st.subheader(\"Kalkulasi Proporsi 1 Sampel\")\n",
    "        n = st.number_input(\"Masukkan n (ukuran sampel):\", min_value=1, step=1, value=50)\n",
    "        x = st.number_input(\"Masukkan x (jumlah keberhasilan):\", min_value=0, step=1, value=30)\n",
    "        p0 = st.number_input(\"Masukkan p0 (proporsi H0):\", min_value=0.0, max_value=1.0, value=0.5, step=0.01)\n",
    "        alt = st.selectbox(\"Pilih alternatif H1:\", (\"two-sided\", \"greater\", \"less\"))\n",
    "        if st.button(\"Hitung Z & p-value (Proporsi 1 sampel)\"):\n",
    "            phat = x / n\n",
    "            se = math.sqrt(p0 * (1 - p0) / n)\n",
    "            z = (phat - p0) / se\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"phat = {phat:.4f}\")\n",
    "            st.write(f\"Z = {z:.4f}\")\n",
    "            st.write(f\"p-value (berdasarkan alternatif '{alt}') ≈ {p:.6f}\")\n",
    "            st.info(\"Keputusan: Bandingkan p-value dengan alpha (mis. 0.05) atau gunakan nilai kritis z.\")\n",
    "    # NILAI KRITIS / PVALUE\n",
    "    with tabs[6]:\n",
    "        st.write(\"Menentukan nilai kritis untuk z:\")\n",
    "        alpha = st.number_input(\"Alpha (signifikansi):\", min_value=0.0001, max_value=0.5, value=0.05, step=0.01)\n",
    "        if st.button(\"Tampilkan nilai kritis z\"):\n",
    "            if st.session_state.get('last_z') is None:\n",
    "                st.write(\"Nilai z/hitung pada tab Kalkulasi untuk membandingkan.\")\n",
    "            z_crit_two = abs(stats.norm.ppf(alpha/2)) if SCIPY_AVAILABLE else abs(math.sqrt(2) * math.erfinv(1 - alpha))\n",
    "            # note: math.erfinv may not be present in Python <3.8; using scipy preferable\n",
    "            try:\n",
    "                if SCIPY_AVAILABLE:\n",
    "                    z_crit_2 = abs(stats.norm.ppf(alpha/2))\n",
    "                    z_crit_upper = stats.norm.ppf(1-alpha)\n",
    "                    st.write(f\"Two-sided z critical ≈ ±{z_crit_2:.4f}\")\n",
    "                    st.write(f\"One-sided z critical ≈ {z_crit_upper:.4f} (upper)\")\n",
    "                else:\n",
    "                    st.warning(\"SciPy tidak tersedia — nilai kritis dihitung dengan aproksimasi.\")\n",
    "            except Exception:\n",
    "                st.warning(\"Silakan install scipy untuk nilai kritis numerik yang akurat.\")\n",
    "    # FLOWCHART\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart referensi untuk memilih uji proporsi: (lihat panel Flowchart utama atau unggah file)\")\n",
    "        st.info(\"Biasanya: apakah parameter proporsi? → apakah sampel 1 atau 2? → gunakan z-test proporsi.\")\n",
    "\n",
    "# 2) Uji Proporsi 2 Sampel\n",
    "if test_menu == \"Uji Proporsi 2 Sampel\":\n",
    "    st.header(\"Uji Proporsi 2 Sampel\")\n",
    "    tabs = render_common_tabs(\"Proporsi 2 Sampel\")\n",
    "    with tabs[0]:\n",
    "        st.markdown(\"Uji untuk membandingkan dua proporsi populasi p1 dan p2 (independen).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: p_1 = p_2\")\n",
    "        st.latex(r\"H_1: p_1 \\ne p_2 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"\\hat{p}_1 = x_1 / n_1,\\quad \\hat{p}_2 = x_2 / n_2\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{x_1 + x_2}{n_1 + n_2}\")\n",
    "        st.latex(r\"Z = \\frac{\\hat{p}_1 - \\hat{p}_2}{\\sqrt{\\hat{p}(1-\\hat{p})(\\frac{1}{n_1}+\\frac{1}{n_2})}}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: x1,x2,n1,n2, alternatif\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh: x1=30,n1=100 ; x2=20,n2=100\")\n",
    "        p1 = 30/100; p2 = 20/100; p_pooled = (30+20)/(100+100)\n",
    "        z = (p1-p2)/math.sqrt(p_pooled*(1-p_pooled)*(1/100+1/100))\n",
    "        st.write(f\"Z ≈ {z:.4f}, p(two-sided)≈{two_sided_p_from_z(z):.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.subheader(\"Kalkulasi Proporsi 2 Sampel\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=1, step=1, value=50, key=\"n1_prop2\")\n",
    "        x1 = st.number_input(\"x1:\", min_value=0, step=1, value=25, key=\"x1_prop2\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=1, step=1, value=50, key=\"n2_prop2\")\n",
    "        x2 = st.number_input(\"x2:\", min_value=0, step=1, value=20, key=\"x2_prop2\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_prop2\")\n",
    "        if st.button(\"Hitung (Proporsi 2 sampel)\"):\n",
    "            p1 = x1/n1; p2 = x2/n2\n",
    "            p_pool = (x1 + x2) / (n1 + n2)\n",
    "            se = math.sqrt(p_pool*(1-p_pool)*(1/n1 + 1/n2))\n",
    "            z = (p1 - p2) / se\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"p1={p1:.4f}, p2={p2:.4f}, Z={z:.4f}, p-value({alt})≈{p:.6f}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Menentukan nilai kritis z sama seperti uji proporsi 1 sampel.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: pilih proporsi → 2 sampel → gunakan pooled prop formula & z-test.\")\n",
    "\n",
    "# 3) Uji Rata-rata 1 Sampel (z jika sigma diketahui)\n",
    "if test_menu == \"Uji Rata-rata 1 Sampel (z jika σ diketahui)\":\n",
    "    st.header(\"Uji Rata-rata 1 Sampel (σ diketahui → Z-test)\")\n",
    "    tabs = render_common_tabs(\"1-Sample Mean (Z)\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila populasi variance (σ^2) diketahui atau sampel besar (n besar).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu = \\mu_0\")\n",
    "        st.latex(r\"H_1: \\mu \\ne \\mu_0 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"Z = \\frac{\\bar{x} - \\mu_0}{\\sigma / \\sqrt{n}}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbar, mu0, sigma, n\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh: xbar=52, mu0=50, sigma=5, n=36\")\n",
    "        z = (52-50)/(5/math.sqrt(36))\n",
    "        st.write(f\"Z = {z:.4f}, p(two-sided)≈{two_sided_p_from_z(z):.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Z 1-sample\")\n",
    "        xbar = st.number_input(\"Masukkan x̄:\", value=0.0, key=\"xbar_z1\")\n",
    "        mu0 = st.number_input(\"Masukkan µ0:\", value=0.0, key=\"mu0_z1\")\n",
    "        sigma = st.number_input(\"Masukkan σ (populasi):\", min_value=0.0001, value=1.0, key=\"sigma_z1\")\n",
    "        n = st.number_input(\"Masukkan n:\", min_value=1, step=1, value=30, key=\"n_z1\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_z1\")\n",
    "        if st.button(\"Hitung Z (1 sample)\"):\n",
    "            z = (xbar - mu0) / (sigma / math.sqrt(n))\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"Z = {z:.4f}, p-value({alt}) ≈ {p:.6f}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis z bisa dilihat dari distribusi normal (mis. ±1.96 untuk α=0.05 two-sided).\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: parameter rata-rata, sigma diketahui? → Z-test jika ya.\")\n",
    "\n",
    "# 4) Uji t 1 Sampel (sigma tidak diketahui)\n",
    "if test_menu == \"Uji t 1 Sampel (σ tidak diketahui)\":\n",
    "    st.header(\"Uji t 1 Sampel (σ tidak diketahui)\")\n",
    "    tabs = render_common_tabs(\"1-sample t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila σ populasi tidak diketahui dan n relatif kecil; gunakan s (sample sd).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu = \\mu_0\")\n",
    "        st.latex(r\"H_1: \\mu \\ne \\mu_0 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"t = \\frac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}, \\quad df = n - 1\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: data sampel (atau x̄ & s & n), µ0\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh (data langsung): gunakan data = [..]\")\n",
    "        st.write(\"Contoh singkat: xbar=5.2, s=1.1, n=10, mu0=5 => t = (5.2-5)/(1.1/√10)\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi t 1-sample\")\n",
    "        data_input = st.text_area(\"Masukkan data (pisahkan koma) atau kosongkan untuk input x̄, s, n\", value=\"\")\n",
    "        mu0 = st.number_input(\"Masukkan µ0:\", value=0.0, key=\"mu0_t1\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_t1\")\n",
    "        if st.button(\"Hitung t 1-sample\"):\n",
    "            try:\n",
    "                if data_input.strip():\n",
    "                    arr = np.array(list(map(float, data_input.split(\",\"))))\n",
    "                    n = len(arr)\n",
    "                    xbar = arr.mean()\n",
    "                    s = arr.std(ddof=1)\n",
    "                else:\n",
    "                    xbar = st.number_input(\"Masukkan x̄:\", value=0.0, key=\"xbar_t1_manual\")\n",
    "                    s = st.number_input(\"Masukkan s (sample sd):\", min_value=0.0001, value=1.0, key=\"s_t1_manual\")\n",
    "                    n = st.number_input(\"Masukkan n:\", min_value=2, step=1, value=10, key=\"n_t1_manual\")\n",
    "                t_stat = (xbar - mu0) / (s / math.sqrt(n))\n",
    "                df = n - 1\n",
    "                if SCIPY_AVAILABLE:\n",
    "                    if alt == \"two-sided\":\n",
    "                        p = 2 * stats.t.sf(abs(t_stat), df)\n",
    "                    elif alt == \"greater\":\n",
    "                        p = stats.t.sf(t_stat, df)\n",
    "                    else:\n",
    "                        p = stats.t.cdf(t_stat, df)\n",
    "                    st.write(f\"t = {t_stat:.4f}, df = {df}, p-value ({alt}) = {p:.6f}\")\n",
    "                else:\n",
    "                    st.write(\"t = {:.4f}, df = {}\".format(t_stat, df))\n",
    "                    st.warning(\"Untuk p-value akurat, install scipy (pip install scipy).\")\n",
    "            except Exception as e:\n",
    "                st.error(f\"Error: {e}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis t didapat dari distribusi t dengan df = n-1 (gunakan tabel t atau scipy.stats.t.ppf).\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: µ? sigma diketahui? jika tidak → gunakan t 1-sample.\")\n",
    "\n",
    "# 5) Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Uji Z)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Z)\":\n",
    "    st.header(\"Uji Rata-rata 2 Sampel Independen — Varians Diketahui (Z-test)\")\n",
    "    tabs = render_common_tabs(\"2-sample mean z\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila kedua populasi varians diketahui (jarang), atau aproksimasi untuk n besar.\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_1 = \\mu_2\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne \\mu_2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"Z = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbar1,xbar2, sigma1, sigma2, n1,n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: x1bar=10, x2bar=8, sigma1=2, sigma2=3, n1=40, n2=35\")\n",
    "        z = (10-8)/math.sqrt(2**2/40 + 3**2/35)\n",
    "        st.write(f\"Z ≈ {z:.4f}, p(two-sided)≈{two_sided_p_from_z(z):.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Z 2-sample (varians diketahui)\")\n",
    "        x1 = st.number_input(\"x̄1:\", value=0.0, key=\"x1_z2\")\n",
    "        x2 = st.number_input(\"x̄2:\", value=0.0, key=\"x2_z2\")\n",
    "        s1 = st.number_input(\"σ1 (populasi):\", min_value=0.0001, value=1.0, key=\"sig1_z2\")\n",
    "        s2 = st.number_input(\"σ2 (populasi):\", min_value=0.0001, value=1.0, key=\"sig2_z2\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=1, step=1, value=30, key=\"n1_z2\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=1, step=1, value=30, key=\"n2_z2\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_z2\")\n",
    "        if st.button(\"Hitung Z (2-sample known var)\"):\n",
    "            z = (x1 - x2) / math.sqrt(s1**2 / n1 + s2**2 / n2)\n",
    "            p = one_sided_p_from_z(z, alt)\n",
    "            st.write(f\"Z = {z:.4f}, p-value ({alt}) ≈ {p:.6f}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis sama dengan uji z lainnya.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: dua sampel independen & varians diketahui -> gunakan z-test 2 sampel.\")\n",
    "\n",
    "# 6) Uji Kesamaan Varians (F-test)\n",
    "if test_menu == \"Uji Kesamaan Varians (F-test)\":\n",
    "    st.header(\"Uji Kesamaan Varians (F-test)\")\n",
    "    tabs = render_common_tabs(\"F-test\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Uji F untuk membandingkan dua varians: H0: σ1^2 = σ2^2\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\sigma_1^2 = \\sigma_2^2\")\n",
    "        st.latex(r\"H_1: \\sigma_1^2 \\ne \\sigma_2^2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"F = \\frac{s_1^2}{s_2^2}, \\quad df_1 = n_1-1, \\ df_2 = n_2-1\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: sample variances s1^2, s2^2, n1, n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: s1^2=4, s2^2=2, n1=10, n2=12\")\n",
    "        F = 4/2\n",
    "        st.write(f\"F = {F:.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi F-test\")\n",
    "        s1sq = st.number_input(\"s1^2 (var sampel 1):\", min_value=0.0, value=4.0, key=\"s1sq\")\n",
    "        s2sq = st.number_input(\"s2^2 (var sampel 2):\", min_value=0.0, value=2.0, key=\"s2sq\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=2, step=1, value=10, key=\"n1_f\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=2, step=1, value=12, key=\"n2_f\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_f\")\n",
    "        if st.button(\"Hitung F\"):\n",
    "            if s2sq == 0:\n",
    "                st.error(\"s2^2 tidak boleh 0.\")\n",
    "            else:\n",
    "                F = s1sq / s2sq\n",
    "                df1 = n1 - 1\n",
    "                df2 = n2 - 1\n",
    "                st.write(f\"F = {F:.4f}, df1={df1}, df2={df2}\")\n",
    "                if SCIPY_AVAILABLE:\n",
    "                    if alt == \"two-sided\":\n",
    "                        # two-sided: p = 2 * min(P(F>f), P(F<f))\n",
    "                        p_upper = stats.f.sf(F, df1, df2)\n",
    "                        p_lower = stats.f.cdf(F, df1, df2)\n",
    "                        p = 2 * min(p_upper, p_lower)\n",
    "                    elif alt == \"greater\":\n",
    "                        p = stats.f.sf(F, df1, df2)\n",
    "                    else:\n",
    "                        p = stats.f.cdf(F, df1, df2)\n",
    "                    st.write(f\"p-value ({alt}) = {p:.6f}\")\n",
    "                else:\n",
    "                    st.warning(\"Untuk p-value akurat, install scipy (pip install scipy).\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Menentukan nilai kritis F: gunakan tabel F atau scipy.stats.f.ppf.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika membandingkan varians dua sampel → gunakan F-test untuk check equal variances.\")\n",
    "\n",
    "# 7) Pooled t-test (equal variances)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Independen — Varians Sama (Pooled t-test)\":\n",
    "    st.header(\"Pooled t-test (Two-sample t, equal variances)\")\n",
    "    tabs = render_common_tabs(\"Pooled t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Untuk dua sampel independen dengan asumsi varians populasi sama.\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_1 = \\mu_2\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne \\mu_2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"s_p^2 = \\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}\")\n",
    "        st.latex(r\"t = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}},\\quad df = n_1+n_2-2\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbar1,xbar2,s1,s2,n1,n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: x1bar=5, x2bar=3, s1=1.2, s2=1.1, n1=12, n2=10\")\n",
    "        sp2 = ((12-1)*1.2**2 + (10-1)*1.1**2) / (12+10-2)\n",
    "        t = (5-3)/(math.sqrt(sp2)*math.sqrt(1/12+1/10))\n",
    "        st.write(f\"t ≈ {t:.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Pooled t\")\n",
    "        x1 = st.number_input(\"x̄1:\", value=0.0, key=\"x1_pt\")\n",
    "        x2 = st.number_input(\"x̄2:\", value=0.0, key=\"x2_pt\")\n",
    "        s1 = st.number_input(\"s1 (sd sampel):\", min_value=0.0001, value=1.0, key=\"s1_pt\")\n",
    "        s2 = st.number_input(\"s2 (sd sampel):\", min_value=0.0001, value=1.0, key=\"s2_pt\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=2, step=1, value=12, key=\"n1_pt\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=2, step=1, value=10, key=\"n2_pt\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_pt\")\n",
    "        if st.button(\"Hitung Pooled t\"):\n",
    "            sp2 = ((n1-1)*s1**2 + (n2-1)*s2**2) / (n1 + n2 - 2)\n",
    "            sp = math.sqrt(sp2)\n",
    "            t_stat = (x1 - x2) / (sp * math.sqrt(1/n1 + 1/n2))\n",
    "            df = n1 + n2 - 2\n",
    "            if SCIPY_AVAILABLE:\n",
    "                if alt == \"two-sided\":\n",
    "                    p = 2 * stats.t.sf(abs(t_stat), df)\n",
    "                elif alt == \"greater\":\n",
    "                    p = stats.t.sf(t_stat, df)\n",
    "                else:\n",
    "                    p = stats.t.cdf(t_stat, df)\n",
    "                st.write(f\"t = {t_stat:.4f}, df = {df}, p-value ({alt}) = {p:.6f}\")\n",
    "            else:\n",
    "                st.write(f\"t = {t_stat:.4f}, df = {df}\")\n",
    "                st.warning(\"Install scipy untuk p-value akurat.\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis t: gunakan t-table atau scipy.stats.t.ppf dengan df = n1+n2-2.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika equal variances TRUE → gunakan pooled t-test.\")\n",
    "\n",
    "# 8) Welch t-test (varians tidak sama)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Independen — Varians Tidak Sama (Welch t-test)\":\n",
    "    st.header(\"Welch t-test (Two-sample t, unequal variances)\")\n",
    "    tabs = render_common_tabs(\"Welch t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan bila varians populasi kedua kelompok tidak sama.\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_1 = \\mu_2\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne \\mu_2\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{s_1^2/n_1 + s_2^2/n_2}}\")\n",
    "        st.latex(r\"\\nu \\approx \\frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\\frac{(s_1^2/n_1)^2}{n_1-1} + \\frac{(s_2^2/n_2)^2}{n_2-1}}  \\quad \\text{(Welch–Satterthwaite)}\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: xbars, s1,s2, n1,n2\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: x1bar=8, x2bar=6, s1=2, s2=3, n1=15, n2=12\")\n",
    "        t = (8-6)/math.sqrt(2**2/15 + 3**2/12)\n",
    "        st.write(f\"t ≈ {t:.4f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Welch t\")\n",
    "        x1 = st.number_input(\"x̄1:\", value=0.0, key=\"x1_welch\")\n",
    "        x2 = st.number_input(\"x̄2:\", value=0.0, key=\"x2_welch\")\n",
    "        s1 = st.number_input(\"s1 (sd):\", min_value=0.0001, value=1.0, key=\"s1_welch\")\n",
    "        s2 = st.number_input(\"s2 (sd):\", min_value=0.0001, value=1.0, key=\"s2_welch\")\n",
    "        n1 = st.number_input(\"n1:\", min_value=2, step=1, value=15, key=\"n1_welch\")\n",
    "        n2 = st.number_input(\"n2:\", min_value=2, step=1, value=12, key=\"n2_welch\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_welch\")\n",
    "        if st.button(\"Hitung Welch t\"):\n",
    "            numerator = (s1**2 / n1 + s2**2 / n2)**2\n",
    "            denom = ( (s1**2 / n1)**2 / (n1 - 1) ) + ( (s2**2 / n2)**2 / (n2 - 1) )\n",
    "            df_approx = numerator / denom if denom != 0 else 1\n",
    "            t_stat = (x1 - x2) / math.sqrt(s1**2 / n1 + s2**2 / n2)\n",
    "            if SCIPY_AVAILABLE:\n",
    "                if alt == \"two-sided\":\n",
    "                    p = 2 * stats.t.sf(abs(t_stat), df_approx)\n",
    "                elif alt == \"greater\":\n",
    "                    p = stats.t.sf(t_stat, df_approx)\n",
    "                else:\n",
    "                    p = stats.t.cdf(t_stat, df_approx)\n",
    "                st.write(f\"t = {t_stat:.4f}, df ≈ {df_approx:.2f}, p-value({alt}) = {p:.6f}\")\n",
    "            else:\n",
    "                st.write(f\"t = {t_stat:.4f}, df ≈ {df_approx:.2f}\")\n",
    "                st.warning(\"Install scipy untuk p-value akurat.\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis: gunakan distribusi t dengan df ditentukan oleh formula Welch–Satterthwaite.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika equal variances FALSE → gunakan Welch t-test.\")\n",
    "\n",
    "# 9) Paired t-test (dependent samples)\n",
    "if test_menu == \"Uji Rata-rata 2 Sampel Dependen (Paired t-test)\":\n",
    "    st.header(\"Paired t-test (2-sample dependent)\")\n",
    "    tabs = render_common_tabs(\"Paired t\")\n",
    "    with tabs[0]:\n",
    "        st.write(\"Digunakan ketika observasi berpasangan (mis. sebelum-sesudah pada subjek yang sama).\")\n",
    "    with tabs[1]:\n",
    "        st.latex(r\"H_0: \\mu_d = 0 \\quad \\text{(sering)}\")\n",
    "        st.latex(r\"H_1: \\mu_d \\ne 0 \\text{ (atau >, <)}\")\n",
    "    with tabs[2]:\n",
    "        st.latex(r\"d_i = x_i - y_i,\\quad \\bar{d} = \\frac{1}{n}\\sum d_i\")\n",
    "        st.latex(r\"t = \\frac{\\bar{d} - \\mu_{d,0}}{s_d / \\sqrt{n}},\\quad df = n-1\")\n",
    "    with tabs[3]:\n",
    "        st.write(\"Parameter: pasangan data X dan Y (per baris), atau masukkan beda secara langsung.\")\n",
    "    with tabs[4]:\n",
    "        st.write(\"Contoh singkat: X = [10,12,11], Y = [9,11,10] → d=[1,1,1] → t ...\")\n",
    "        d = np.array([1,1,1])\n",
    "        st.write(f\"d mean = {d.mean():.3f}, sd(d) = {d.std(ddof=1):.3f}\")\n",
    "    with tabs[5]:\n",
    "        st.header(\"Kalkulasi Paired t\")\n",
    "        data_X = st.text_area(\"Masukkan data X (pisahkan koma):\", value=\"\")\n",
    "        data_Y = st.text_area(\"Masukkan data Y (pisahkan koma):\", value=\"\")\n",
    "        mu_d0 = st.number_input(\"µ_d0 (null difference):\", value=0.0, key=\"mud0\")\n",
    "        alt = st.selectbox(\"Alternatif H1:\", (\"two-sided\", \"greater\", \"less\"), key=\"alt_paired\")\n",
    "        if st.button(\"Hitung Paired t\"):\n",
    "            try:\n",
    "                X = np.array(list(map(float, data_X.split(\",\"))))\n",
    "                Y = np.array(list(map(float, data_Y.split(\",\"))))\n",
    "                if len(X) != len(Y):\n",
    "                    st.error(\"Panjang data X dan Y harus sama.\")\n",
    "                else:\n",
    "                    d = X - Y\n",
    "                    n = len(d)\n",
    "                    dbar = d.mean()\n",
    "                    sd = d.std(ddof=1)\n",
    "                    t_stat = (dbar - mu_d0) / (sd / math.sqrt(n))\n",
    "                    df = n - 1\n",
    "                    if SCIPY_AVAILABLE:\n",
    "                        if alt == \"two-sided\":\n",
    "                            p = 2 * stats.t.sf(abs(t_stat), df)\n",
    "                        elif alt == \"greater\":\n",
    "                            p = stats.t.sf(t_stat, df)\n",
    "                        else:\n",
    "                            p = stats.t.cdf(t_stat, df)\n",
    "                        st.write(f\"t = {t_stat:.4f}, df = {df}, p-value({alt}) = {p:.6f}\")\n",
    "                    else:\n",
    "                        st.write(f\"t = {t_stat:.4f}, df = {df}\")\n",
    "                        st.warning(\"Install scipy untuk p-value akurat.\")\n",
    "            except Exception as e:\n",
    "                st.error(f\"Error parsing data: {e}\")\n",
    "    with tabs[6]:\n",
    "        st.write(\"Nilai kritis t: gunakan t-table dengan df = n-1.\")\n",
    "    with tabs[7]:\n",
    "        st.write(\"Flowchart: jika dua sampel dependen → gunakan paired t-test.\")\n",
    "\n",
    "# Footer / help\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\n",
    "    \"**Catatan:***\\n\"\n",
    "    \"- Pastikan memahami asumsi tiap uji (normalitas, independensi, ukuran sampel, dsb.).\\n\"\n",
    "    \"- Untuk p-value distribusi t/F presisi, sebaiknya install `scipy` (`pip install scipy`).\\n\"\n",
    "    \"- Aplikasi ini menampilkan rumus, contoh singkat, dan kalkulator interaktif untuk membantu penentuan uji.\\n\"\n",
    "    \"- Jika kamu punya flowchart yang diberikan dosen, unggah di menu **Flowchart** untuk referensi kelompok.\"\n",
    ")\n",
    "if not SCIPY_AVAILABLE:\n",
    "    st.warning(\"Modul scipy tidak tersedia pada environment ini — beberapa p-value (t, F) tidak dihitung otomatis. \"\n",
    "               \"Install scipy untuk hasil numerik lengkap: pip install scipy\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62e4c725-3e56-44c4-ae6e-81212b3fdd4d",
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run uji_hipotesis_streamlit.py"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
